development:
  adapter: postgresql
  encoding: unicode
  database: betty_development
  pool: 5
  username: frodsan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: betty_test
  pool: 5
  username: frodsan
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: betty_production
  pool: 5
  username: frodsan
  password:
