defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USER'] %>
  password:

development:
  <<: *defaults
  database: plataforma_development

test:
  <<: *defaults
  database: plataforma_test

production:
  <<: *defaults
  database: plataforma_production
