development:
  adapter: postgresql
  encoding: unicode
  database: barney_development
  pool: 5
  username: frodsan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: barney_test
  pool: 5
  username: frodsan
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: barney_production
  pool: 5
  username: frodsan
  password:
